version: '3'
services:
  mssqlserver:
    container_name: mssqlserver
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MARIADB_DATABASE=company
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=aminakoydum
      - MARIADB_PASSWORD=soktum
    volumes:
      - ./docker/mssql/temp:/docker-entrypoint-initdb.d

  php:
    container_name: db2_labor_ss21_encoit01-php
    build:
      context: docker/php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    links:
      - mssqlserver


  nginx:
    container_name: db2_labor_ss21_encoit01-nginx
    build:
      context: docker/nginx
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:/var/www
    links:
      - php


  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mssqlserver
    restart: always
    depends_on:
      - "mssqlserver"

